version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: detache_db
    restart: always
    environment:
      POSTGRES_DB: detache_db
      POSTGRES_USER: detache_user
      POSTGRES_PASSWORD: detache_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U detache_user -d detache_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: detache_backend
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-detache-secret-key-development
      - DEBUG=True
      - ALLOWED_HOSTS=127.0.0.1,localhost,host.docker.internal,157.245.82.247,https://www.detache.cl/,https://pianoacademy-git-main-jsepulvedai1s-projects.vercel.app
      - CORS_ALLOW_ALL_ORIGINS=True
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=detache_db
      - DB_USER=detache_user
      - DB_PASSWORD=detache_password
      - DB_HOST=db
      - DB_PORT=5432
      - EVOLUTION_API_URL=http://157.245.82.247:8080
      - EVOLUTION_API_KEY=admin_apikey_123
      - EVOLUTION_INSTANCE_NAME=MainInstance
      - OLLAMA_URL=http://host.docker.internal:11434/api/generate
      - OLLAMA_MODEL=llama3.2:3b
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
