# Generated by Django 4.2.29 on 2026-04-23 07:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_student_phone_number_teacher_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('servicio', models.CharField(choices=[('PIANO_NINOS', 'Piano Niños'), ('PIANO_ADULTOS', 'Piano Adultos'), ('CANTO', 'Canto'), ('CLASE_GRUPAL', 'Clase Grupal'), ('CLASE_PRUEBA', 'Clase de Prueba')], default='CLASE_PRUEBA', max_length=50)),
                ('fuente', models.CharField(choices=[('WEB', 'Web'), ('WHATSAPP', 'WhatsApp'), ('INSTAGRAM', 'Instagram'), ('REFERIDO', 'Referido'), ('GOOGLE', 'Google'), ('OTRO', 'Otro')], default='WEB', max_length=50)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo Lead'), ('CONTACTADO', 'Contactado'), ('SEGUIMIENTO', 'Seguimiento'), ('PRE_RESERVA', 'Pre-reserva'), ('RESERVA_CONFIRMADA', 'Reserva Confirmada'), ('CONCRETADO', 'Concretado (Alumno)'), ('SIN_RESPUESTA', 'Sin Respuesta'), ('LISTA_ESPERA', 'Lista de Espera'), ('NO_CONCRETADO', 'No Concretado')], default='NUEVO', max_length=50)),
                ('asignado_a', models.CharField(blank=True, default='Recepción', max_length=100, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_contacto', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_pre_reservation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='classes_count',
            field=models.PositiveIntegerField(default=4, help_text='Number of classes included in this pack (e.g., 4, 12, 24)'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='primary_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.instrument'),
        ),
        migrations.AddField(
            model_name='student',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='StudentPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_classes', models.PositiveIntegerField()),
                ('remaining_classes', models.PositiveIntegerField()),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.plan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('method', models.CharField(choices=[('TRANSFER', 'Transferencia'), ('CASH', 'Efectivo'), ('CARD', 'Tarjeta')], default='TRANSFER', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.studentpack')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('autor', models.CharField(default='Sistema', max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='api.lead')),
            ],
        ),
    ]
