# Generated by Django 4.2.29 on 2026-04-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_lead_lesson_created_at_lesson_is_pre_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark as recommended plan on landing page'),
        ),
    ]
