# Generated by Django 4.2.29 on 2026-04-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_dashboardnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('assigned_to', models.CharField(choices=[('VENTAS', 'Ventas'), ('RECEPCION', 'Recepción'), ('ADMINISTRACION', 'Administración')], default='RECEPCION', max_length=50)),
                ('priority', models.CharField(choices=[('URGENTE', 'Urgente'), ('IMPORTANTE', 'Importante'), ('RECORDATORIO', 'Recordatorio'), ('INFORMATIVO', 'Informativo')], default='RECORDATORIO', max_length=50)),
                ('log', models.TextField(blank=True, help_text='Bitácora de acciones', null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['is_completed', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DashboardNote',
        ),
    ]
