# Generated by Django 4.2.29 on 2026-05-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_material_studentwallmessage_studentprivatenote'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('benefits', models.JSONField(default=list)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('cta', models.CharField(max_length=100)),
            ],
        ),
    ]
