# Generated by Django 4.2.29 on 2026-05-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_landingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.CharField(default='/images/piano-hero.png', max_length=500)),
                ('hero_title_1', models.CharField(default='Detaché:', max_length=255)),
                ('hero_title_highlight', models.CharField(default='El Arte', max_length=255)),
                ('hero_title_2', models.CharField(default='de Dominar la música', max_length=255)),
                ('hero_subtitle', models.TextField(default='Eleva tu técnica y sensibilidad artística con formación de primer nivel.')),
                ('hero_cta1_text', models.CharField(default='Solicitar Clase de Prueba', max_length=100)),
                ('hero_cta1_link', models.CharField(default='/book', max_length=200)),
                ('hero_cta2_text', models.CharField(default='Nuestros Maestros', max_length=100)),
                ('hero_cta2_link', models.CharField(default='/teachers', max_length=200)),
                ('features', models.JSONField(default=list)),
                ('method_badge', models.CharField(default='Nuestro Método Técnico', max_length=100)),
                ('method_title', models.TextField(default='No son clases sueltas, es un proceso de maestría')),
                ('method_description', models.TextField(default='En Détaché, no creemos en el aprendizaje fragmentado.')),
                ('method_items', models.JSONField(default=list)),
                ('method_image', models.CharField(default='/images/method.png', max_length=500)),
                ('testimonials', models.JSONField(default=list)),
                ('location_title', models.CharField(default='Estamos cerca de ti', max_length=255)),
                ('location_description', models.TextField(default='Nuestra academia se encuentra en un punto estratégico.')),
                ('location_address', models.CharField(default='Av. Música 123, Piso 2, Providencia', max_length=255)),
                ('location_address_detail', models.CharField(default='A pasos de Metro Salvador', max_length=255)),
                ('location_map_url', models.CharField(default='https://maps.google.com', max_length=500)),
                ('final_cta_title', models.CharField(default='¿Listo para empezar?', max_length=255)),
                ('final_cta_description', models.TextField(default='Déjanos tus datos y te contactaremos para agendar tu primera experiencia.')),
                ('final_cta_button_text', models.CharField(default='Solicitar Clase de Prueba', max_length=100)),
            ],
            options={
                'verbose_name': 'Contenido del Homepage',
            },
        ),
    ]
