# Generated by Django 4.2.29 on 2026-06-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_homepagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_subtitle',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_title_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_title_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_title_highlight',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='location_address',
            field=models.CharField(default='Gran Avenida José Miguel Carrera 8520, Of. C, La Cisterna', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='location_address_detail',
            field=models.CharField(default='A pasos de Metro La Cisterna', max_length=255),
        ),
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=45)),
                ('price', models.IntegerField(default=0)),
                ('currency', models.CharField(default='CLP', max_length=10)),
                ('allowed_levels', models.JSONField(default=list)),
                ('allowed_modalities', models.JSONField(default=list)),
                ('what_you_will_learn', models.JSONField(default=list)),
                ('teachers', models.ManyToManyField(blank=True, related_name='class_types', to='api.teacher')),
            ],
        ),
    ]
