# Generated by Django 4.2.29 on 2026-06-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_homepagecontent_hero_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
