# Generated by Django 4.2.29 on 2026-07-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_plan_benefits'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.CharField(default='/imagesfooter/4.png', max_length=500)),
                ('hero_title_highlight_1', models.CharField(default='Aprender', max_length=255)),
                ('hero_title_text_1', models.CharField(default='música debe ser una experiencia', max_length=255)),
                ('hero_title_highlight_2', models.CharField(default='clara y motivadora.', max_length=255)),
                ('history_image', models.CharField(default='/imagesfooter/2.png', max_length=500)),
                ('history_title', models.CharField(default='Nuestra Historia', max_length=255)),
                ('history_subtitle', models.TextField(default='Academia Detaché nació para transformar la frustración de aprender música en un camino claro y disfrutable.')),
                ('history_description', models.TextField(default='Cansados de la improvisación, creamos en el sector sur de Santiago un método estructurado, cercano y apasionado que garantiza un avance real, poniendo siempre el progreso y el bienestar del alumno en el centro de nuestra historia.')),
                ('moving_title', models.CharField(default='Lo que nos Mueve', max_length=255)),
                ('moving_description', models.TextField(default='Nuestra forma de enseñar nace del amor por la música y del compromiso con cada estudiante.')),
                ('moving_cards', models.JSONField(default=list)),
                ('team_title', models.CharField(default='Nuestro Equipo', max_length=255)),
                ('team_description', models.TextField(default='Detrás de cada clase hay personas que disfrutan enseñar y compartir su pasión por la música.')),
                ('team_images', models.JSONField(default=list)),
                ('final_title_1', models.CharField(default='Conoce una', max_length=255)),
                ('final_title_2', models.CharField(default='nueva forma', max_length=255)),
                ('final_title_3', models.CharField(default='de aprender', max_length=255)),
                ('final_image', models.CharField(default='/nosotros/4.png', max_length=500)),
            ],
            options={
                'verbose_name': 'Contenido de Nosotros',
            },
        ),
        migrations.CreateModel(
            name='ContactContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title_1', models.CharField(default='Sigamos', max_length=255)),
                ('banner_title_2', models.CharField(default='compartiendo', max_length=255)),
                ('banner_title_3', models.CharField(default='el lenguaje de', max_length=255)),
                ('banner_title_4', models.CharField(default='la música', max_length=255)),
                ('location_title', models.CharField(default='Estamos cerca de ti', max_length=255)),
                ('location_description', models.TextField(default='Nuestra academia se encuentra en una ubicación estratégica y de fácil acceso, para que llegar a tus clases sea cómodo y sencillo.')),
                ('location_address_title', models.CharField(default='Dirección Sede', max_length=255)),
                ('location_address', models.TextField(default='Gran Avenida José Miguel Carrera 8520, Oficina C, La Cisterna.')),
                ('location_map_iframe_url', models.TextField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3326.2307849187313!2d-70.6622543!3d-33.5217965!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662dae3cbf5df1f%3A0xe54fb7a71fbd4fdf!2sGran%20Av.%20Jos%C3%A9%20Miguel%20Carrera%208520%2C%20La%20Cisterna%2C%20Regi%C3%B3n%20Metropolitana!5e0!3m2!1ses-419!2scl!4v1700000000000!5m2!1ses-419!2scl')),
            ],
            options={
                'verbose_name': 'Contenido de Contacto',
            },
        ),
    ]
