# Generated by Django 4.2.29 on 2026-07-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_aboutcontent_contactcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='gallery_images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='gallery_title',
            field=models.CharField(default='LA MÚSICA COMO NUNCA TE LA HABÍAN EXPLICADO', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='instruments_description',
            field=models.TextField(default='La música comienza con una primera nota. Nosotros te acompañamos en el resto del camino.'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='instruments_title',
            field=models.CharField(default='Aprende con Nosotros', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='planes_description',
            field=models.TextField(default='Haz espacio para la música en tu vida y encuentra el programa perfecto para ti.'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='planes_title',
            field=models.CharField(default='Nuestros Planes', max_length=255),
        ),
    ]
