# Generated by Django 4.2.29 on 2026-07-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_homepagecontent_gallery_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+56 9 6427 9239', max_length=20)),
                ('email_contact', models.EmailField(default='academia@detache.cl', max_length=254)),
                ('address', models.CharField(default='Gran Avenida José Miguel Carrera 8520, Oficina C, La Cisterna', max_length=255)),
                ('opening_hours_weekdays', models.CharField(default='9:00 - 20:00', max_length=100)),
                ('opening_hours_saturdays', models.CharField(default='10:00 - 14:00', max_length=100)),
                ('facebook_url', models.CharField(default='https://facebook.com', max_length=255)),
                ('instagram_url', models.CharField(default='https://instagram.com/academia.detache', max_length=255)),
                ('trial_class_email_template', models.TextField(default='Hola {nombre},\n\nHemos recibido tu pre-reserva de Clase de Prueba con {profesor} para el {fecha} a las {hora}.\n\nPor favor, ten en cuenta que para confirmar tu cupo debes realizar el pago antes de las 20:00 hrs de hoy. De lo contrario, el horario quedará liberado automáticamente.\n\nSaludos,\nAcademia Détaché')),
            ],
            options={
                'verbose_name': 'Configuración Global',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
